url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "CGU AICV Lab" # the name of your site, e.g. ACME Corp.
description: "Artificial Intelligent Computer Vision Lab at Chang Gung University"
